### ISSUE TITLE
Function already exists error when reload vimrc

### ISSUE THREAD

**Issue by jtr109** [mhartington/oceanic-next#56] opened 2017-07-25 03:02 UTC
# Problems summary

The error `E122: Function <SNR>9_hi already exists, add ! to replace it` raises when vim config file sourced such as using `:source ~/.vimrc`.

## Environment Information

 * terminal: iTerms 2, VimR, etc.
 * vim/nvim version: vim 8.0, nvim v0.2.1-dev

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" My vim rc
" Vim-airline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
let g:airline#extensions#tabline#enabled = 1
set laststatus=2
let g:airline_theme='oceanicnext'
let g:airline_powerline_fonts=1
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

" set Vim-specific sequences for RGB colors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

Plug 'mhartington/oceanic-next'
set runtimepath+=~/.local/share/nvim/plugged/oceanic-next
if (has("termguicolors"))
 set termguicolors
endif

syntax enable
colorscheme OceanicNext
let g:airline_theme='oceanicnext'

```

You can alse find my dotfile from [here](https://github.com/jtr109/dotfile/blob/master/nvim/init.vim).

## Screen shot (if possible)

![screen shot 2017-07-25 at 10 57 41](https://user-images.githubusercontent.com/13946679/28553735-0c6f0a0c-7128-11e7-9e1f-db542eeb8808.png)

## By the way

It is a great theme! 🍻

**Comment by mhartington** [comment] 2017-07-25 13:30
I think the issue is that you're setting things before calling `plug#end()`.

Can you try moving all the settings until after that has been called.

**Comment by jtr109** [comment] 2017-07-25 13:54
Oops!

Do you mean I should put all settings even if the setting for plugin after `plug#end()`?  I will close this issue and have a try. 

Thanks a lot! 😆

**Comment by jtr109** [comment] 2017-07-25 14:57
I'm sorry for reopening it again.

I try to [put all plugs together and take all settings after plug#end()](https://github.com/jtr109/dotfile/commit/ca204c2e1f183ae8c8bd7087b7abdbd21d4f259d#diff-928116dea1f7bf8d37b6fd681fe502e9R1), but it not solved the problem.

I have use your theme for a long time and the error only happened after the latest update. I still think [this line cause the problem](https://github.com/mhartington/oceanic-next/commit/c9eab8c3bd70c1279d1f7a4b67f9f43e1a7e5029#diff-3dda073bca099f48a6fb75a5bc91380eR50). In my opinion, after the vim editor loaded at first time. When I use `:source ~/.vimrc` to re-source the vim config file. The function is redefined and this is why the error raised. [This question on StackOverflow](https://stackoverflow.com/questions/39706615/how-to-fix-this-error-e122-function-mydiff-already-exists-add-to-replace-it) may prove my opinion.

Maybe I am wrong. But still hope for your help. Thank you very much.

**Comment by gcperrin** [comment] 2017-07-25 20:20
+1 same issue for me.

**Comment by mhartington** [comment] 2017-07-25 20:27
Just merged your PR. Yeah, that should fix things.

**Closed as completed** 2017-07-25 20:26 UTC

**Comment by jtr109** [comment] 2017-07-25 23:49
It is my pleasure. 😃
