### ISSUE TITLE
Colors have drastically changed since move to estilo

### ISSUE THREAD

**Issue by JackCA** [mhartington/oceanic-next#33] opened 2016-10-27 21:44 UTC
Hi there,

Since the recent [update to estilo](https://github.com/mhartington/oceanic-next/commit/7cd6e00ba3135bc92ab99075e30c3a8b05bf19fb), I've noticed that a lot of colors have changed in my javascript files:
### Before

<img width="559" alt="screen shot 2016-10-27 at 2 42 56 pm" src="https://cloud.githubusercontent.com/assets/296167/19786619/b75e0896-9c53-11e6-8815-d9952df33cde.png">
### After

<img width="506" alt="screen shot 2016-10-27 at 2 42 26 pm" src="https://cloud.githubusercontent.com/assets/296167/19786620/ba8762e2-9c53-11e6-8fee-dca879540e34.png">

Is this a regression or something unique to my environment?

**Comment by mhartington** [comment] 2016-10-28 00:56
Hmm, how could I reproduce?

Could you provide a minimal vimrc to test against?
Also, whats your env? 
What vim/neovim version?
Can you provide a sample file to test against? 

Comparing the original test file in neovim and vim8 seems to produce the correct colors.

<img width="772" alt="screen shot 2016-10-27 at 8 53 48 pm" src="https://cloud.githubusercontent.com/assets/2835826/19790612/82890164-9c87-11e6-8034-e884256d158d.png">

**Comment by JackCA** [comment] 2016-10-28 22:10
@mhartington with [this `init.vim`](https://gist.github.com/JackCA/0eefe6122ffc64d6c86043cd0eb59efa) and neovim 0.1.5, I get the following on your test file:

![screen shot 2016-10-28 at 2 50 01 pm](https://cloud.githubusercontent.com/assets/296167/19823948/9e795d4e-9d20-11e6-98bf-ff56cff47f15.png)

**Comment by mhartington** [comment] 2016-10-28 23:14
Gah, my bad. You can remove that set background in the rc file. No longer needed with estilo since it sets it in the colors

**Comment by JackCA** [comment] 2016-10-29 17:14
@mhartington this is what happens without `set background=dark`:

<img width="505" alt="screen shot 2016-10-29 at 10 13 55 am" src="https://cloud.githubusercontent.com/assets/296167/19831519/7dd07992-9dc0-11e6-9e4b-33f60ad59f4d.png">

**Comment by mhartington** [comment] 2016-10-29 17:28
K, I'll take a look tonight

**Comment by mhartington** [comment] 2016-10-30 23:08
Hmm, not able to replicate.

``` viml
set runtimepath+=~/.config-test/nvim/repos/github.com/Shougo/dein.vim/
call dein#begin(expand('~/.config-test/nvim'))
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/denite.nvim')
call dein#add('mhartington/oceanic-next')
  if dein#check_install()
    call dein#install()
    let pluginsExist=1
  endif
  call dein#end()
filetype plugin indent on
if (has("termguicolors"))
  set termguicolors
endif
syntax enable
set t_Co=256
colorscheme OceanicNext
```

<img width="761" alt="screen shot 2016-10-30 at 7 05 03 pm" src="https://cloud.githubusercontent.com/assets/2835826/19840747/d924490e-9ed3-11e6-8561-7b23d5d890a0.png">

This looks as expected with vim/neovim's syntax highlighting 

Not sure how you're getting the light version, since it's under a different name, `OceanicNextLight`.

**Comment by JackCA** [comment] 2016-10-30 23:47
@mhartington thanks for looking into it. It looks like our setups are pretty identical except for our plugin manager and the fact that I need to set the background color.

To add additional context, I am using iTerm2 on Mac OS 10.11.

@yosemitebandit, you +1'ed my issue. Can you confirm that you're experiencing this issue as well? If so, what's your minimal setup that recreates the issue?

**Comment by mhartington** [comment] 2016-10-31 00:08
The only thing I could think of then is making sure the plugin is up to date, and if you need to set the background, set it before the colors

**Comment by yosemitebandit** [comment] 2016-10-31 18:03
@JackCA -- yes, when I use `oceanic-next` master I see changes to the text colors and background.  

Before (using `oceanic-next` commit `b938fbcf`):

![screen shot 2016-10-31 at 10 56 47 am](https://cloud.githubusercontent.com/assets/751590/19865319/fd574616-9f58-11e6-81ba-0f01b9fb8504.png)

after:

![screen shot 2016-10-31 at 10 57 23 am](https://cloud.githubusercontent.com/assets/751590/19865334/0a36d70c-9f59-11e6-8444-48a36d02e5e4.png)

I'm also on iTerm2, Mac 10.11.6 and NVIM v0.1.5-702-g4dc4efc.  I'll chime in again if I find a minimal setup to recreate this issue.

**Comment by mhartington** [comment] 2016-11-01 15:07
Yeah, @yosemitebandit if you can provide a minimal rc file to test against, that will help

**Comment by mhartington** [comment] 2016-11-21 16:46
Closing as there hasn't been a reply in 20 days. 
Please open a NEW issue and provide a minimal rc file to test against.

**Closed as completed by mhartington** 2016-11-21 16:46 UTC
